### ISSUE TITLE
Model Weights not Found

### ISSUE THREAD

**Issue by jvel07** [ZFTurbo/MVSEP-CDX23-Cinematic-Sound-Demixing#3]
Hi, congrats on the repo and the solution!
I would love to reproduce your results, could you please point me to where to download the trained models?
Much appreciated!

**Comment by ZFTurbo** [comment]
It's here:
https://github.com/ZFTurbo/MVSEP-CDX23-Cinematic-Sound-Demixing/releases/tag/v.1.0.0
